[package]
name = "timsrust_pyo3"
version = "0.2.0"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "timsrust_pyo3"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
timsrust = "0.2.2"
